version: 2.1

orbs:
  python: circleci/python@1.2
  php: circleci/php@1.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.7
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Run tests
          command: |
            flake8 --ignore=E501
            coverage run -m  pytest -q

workflows:
  sample:
    jobs:
      - build-and-test
